service:
  name: payroll-system

plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10
  environment:
    DB_HOST: ${file(properties.yml):db_host}
    DB_NAME: ${file(properties.yml):db_name}
    DB_USER: ${file(properties.yml):db_user}
    DB_PASSWORD: ${file(properties.yml):db_password}

functions:
  uploadFile:
    handler: src/main/handler.uploadFile
    events:
      - http:
          path: api/uploadFile
          method: post
  getReport:
    handler: src/main/handler.getReport
    events:
      - http:
          path: api/getReport
          method: get
  hello:
    handler: src/main/handler.hello
    events:
      - http:
          method: get
          path: hello
