service:
  name: payroll-system

plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10
  environment:
    PAYROLL_SCHEMA: 'db_payroll'
functions:
  hello:
    handler: src/main/handler.hello
    events:
      - http:
          method: get
          path: hello
